/*
 * Filename: Divide.java
 * Programmer: Karinya Makaew (kmakaew@andrew.cmu.edu)
 * Course: 95-712
 * Assignment: Homework 5 Question 1
 * Deadline: 07/17/2012
 * Description: Given in Blackboard (no modification)
 * 		
 */

/* Generated by Together */

public class Divide extends Binop {
    public Divide() {}
    public Divide(Node l, Node r) {
        super(l, r);
    }
    public double eval(double[] data) {
		//check for zero divisor
		if(rChild.eval(data) == 0) {
			throw new ArithmeticException("Divided by zero");		
		}
		return lChild.eval(data) / rChild.eval(data);
    }
    public String toString() {
        String s = new String();
        s += "(" + lChild.toString() + " / " + rChild.toString() + ")";
        return s;
    }
}
