/*
 * Filename: Variable.java
 * Programmer: Karinya Makaew (kmakaew@andrew.cmu.edu)
 * Course: 95-712
 * Assignment: Homework 5 Question 1
 * Deadline: 07/17/2012
 * Description: Based on the class given in blackboard
 * 				Represent variable in algebra expression
 * 				Does not have any children
 * 				
 */

/* Generated by Together */
import java.util.Random;

public class Variable extends Node {
    private int index;
    public Variable(int i) {
        index = i;
    }
	public void setChild(int position, Node n) {
        System.out.println("Attempt to add child to Variable");
    }
    public String toString() {
        String s = new String();
        s += "X" + index;
        return s;
    }
	public double eval(double[] data) {
        if (index < data.length)
        	return data[index];
        else {
            System.out.println("Variable index exceeds data array length.");
            return 0;
        }
    }
	
	//do not add any kid for variable node
	public void addRandomKids(OperatorFactory o, TerminalFactory t, int maxDepth, Random rand){}

}
