/* Generated by Together */

public abstract class Binop implements Node {
    protected Node lChild, rChild;
    public Binop() {}
    public Binop(Node l, Node r) {
    	lChild = l; rChild = r;
    }
    public void setChild(int position, Node n) {
        if (position == 1)
        	lChild = n;
        else
            rChild = n;
    }
}
